export const ProfileStates: String[]| Object = {
    firstName: '',
    lastName: '',
    birthplace: '',
    birthday: '',
    IDType: '',
    IDNum: '',
    country: '',
    province: '',
    cities: '',
    district: '',
    subdistrict: '',
    countryCurrent: '',
    provinceCurrent: '',
    citiesCurrent: '',
    districtCurrent: '',
    subdistrictCurrent: '',
    educations: [],
    families: [],
    phoneNum: '',
    detLoc: '',
    detLocCurrent: '',
    ava: ''
}